### ISSUE TITLE
`flycheck-pos-tip` fails on terminals

### ISSUE THREAD

**Issue by StreakyCobra** [flycheck/flycheck-pos-tip#11]
With the current implementation, `flycheck-pos-tip` throws an error when emacs is run within a terminal.

```
Flycheck error display error: (error Window system frame should be used)
```

It would be nice to handle this case, maybe with a fallback in the echo area when there is no window system.

See https://github.com/syl20bnr/spacemacs/issues/4111 for reference.

**Comment by lunaryorn** [comment]
We'll fall back to the built-in echo area display on non-graphical display.  The fallback will be customisable.

**Comment by StreakyCobra** [comment]
:+1: Many thanks for your support :-)

**Comment by cpitclaudel** [comment]
@lunaryorn I can make a PR for this one (this week-end) :)

**Comment by lunaryorn** [comment]
@cpitclaudel That would be great!
