### ISSUE TITLE
Increase font size

### ISSUE THREAD

**Issue by soudy** [flycheck/flycheck-pos-tip#20]
Is it possible to change the pop-up's font size? It's really tiny on HiDPI displays.

**Comment by cpitclaudel** [comment]
Sure.  See the following section of the Emacs manual:

> If Emacs is built with GTK+ support, it displays tooltips via GTK+, using the default appearance of GTK+ tooltips. To disable this, change the variable x-gtk-use-system-tooltips to nil. If you do this, or if Emacs is built without GTK+ support, most attributes of the tooltip text are specified by the tooltip face, and by X resources (see X Resources). 

Does this help?

**Comment by cpitclaudel** [comment]
Closing this, since there was no reply; please reopen if you need more help :)
