### ISSUE TITLE
confilct in the HiDPi result the misplaced popup

### ISSUE THREAD

**Issue by bravomikekilo** [flycheck/flycheck-pos-tip#24]
I use a 4k screen. and set the window scaling to 2. result the misplace of the popup tips
![screenshot from 2016-11-27 19-24-07](https://cloud.githubusercontent.com/assets/17548436/20648040/1908e26e-b4d7-11e6-9f1a-cb0ff6be6de8.png)
Every thing works good when the window scaling is set to 1 as default
seems the pos-tip haven't consider the scale

**Comment by bravomikekilo** [comment]
I solve the problem
It seems that there are something wrong with the gtk-tooltip. It haven't consider the window scaling for HiDPi.
so I just set the `x-gtk-use-system-tooltips` to `nil` in the `user-config` to let emacs use its own API.

**Comment by cpitclaudel** [comment]
Please report the problem as an Emacs bug; flycheck is just a client of that API, but I'm sure the Emacs people would love to have it solved.
