### ISSUE TITLE
Pop-up is messed up

### ISSUE THREAD

**Issue by Eilie** [flycheck/flycheck-pos-tip#3]
For some reason flycheck compilation error popup can't be displayed over text so it chooses to add each line of compilation error popup at the end of existing line:
![](http://i.imgur.com/ETbqtzl.png)

Maybe i've built my emacs without some important use flag for this to work properly?

**Comment by lunaryorn** [comment]
Closing due to the lack of activity.  Please open a new issue if the problem persists in the latest MELPA version.
