### ISSUE TITLE
flycheck-pos-tip may block my view / hooks for allowing visualization

### ISSUE THREAD

**Issue by FelipeLema** [flycheck/flycheck-pos-tip#34]
Hello, there

Using lsp-mode, I've come across certain situations in which the pos-tip is appearing, but it's getting in the way. Particularly, it has happened to me while in `evil-insert-state` and with `company` activated.

I'm proposing a two-part solution:
- A hook in which anyone can add functions (closures or symbols) to test whether the tooltip _should_ be displayed. If only one of them says that it shouldn't be displayed, the tooltip won't be shown.
- Add "company is currently being presented" and "currently in `evil-insert-mode`" to this hook

I'm happy with *just the first part*, though

This is a very useful package. Thank you so much for your work on it.

**Comment by cpitclaudel** [comment]
You don't need a separate hook: the recommended design for this sort of stuff these days is `add-function` on the function place `flycheck-display-errors-function`.  You can use `:before-while` with a function that returns `t` if the tooltip should be displayed.

**Comment by FelipeLema** [comment]
I've already done something like that, but I thought adding a hook would help others. 

I guess not, then. Closing then.

Thanks
