### ISSUE TITLE
popup text extremely small

### ISSUE THREAD

**Issue by hsheikhali1** [flycheck/flycheck-pos-tip#35]
Is there a way to increase the tooltip font size? New to emacs so not sure how to do this myself yet

**Comment by cpitclaudel** [comment]
Is it the same size as the text in the menu bar?  If so it's a system text scaling setting. You could try customizing `x-gtk-use-system-tooltips`: http://www.gnu.org/software/emacs/manual/html_node/emacs/Tooltips.html

**Comment by cpitclaudel** [comment]
I'll close the issue since it's an Emacs-wide issue, but I hope the link helps!
