### ISSUE TITLE
Vertical split hides popup

### ISSUE THREAD

**Issue by arichiardi** [flycheck/flycheck-pos-tip#4]
If two buffers are open and split in vertical, then the popup has cut content, like:

![selection_015](https://cloud.githubusercontent.com/assets/1724788/8579218/8df46436-25b3-11e5-9ee0-c7261d60ff5b.png)

Instead of:

![selection_016](https://cloud.githubusercontent.com/assets/1724788/8579232/a4cae932-25b3-11e5-9cb3-3164a09acbbc.png)

**Comment by lunaryorn** [comment]
Closing due to the lack of activity.  Please open a new issue if the problem persists in the latest MELPA version.
