### ISSUE TITLE
Tool-tip not disappearing

### ISSUE THREAD

**Issue by StreakyCobra** [flycheck/flycheck-pos-tip#6]
With the last version, freshly taken from MELPA (20151109.1056), the tool-tip take ages to disappear. It get updated quickly once on a new error (position and text), but even switching to another windows (like firefox) or changing the workspace (in i3) don't close it.

This issue was confirmed by @TheBB, so it shouldn't be config-specific.

**Comment by zeroDivisible** [comment]
Just to add to the above: after setting 

```
(setq
  flycheck-pos-tip-timeout 10)
```

tool-tip will disappear after 10 seconds. 

However, even with the above, it will still not disappear:

* after Emacs looses focus
* after moving a cursor outside of the highlighted part of the code.

**Comment by synic** [comment]
Yeah, this is really annoying.  Going to have to remove this package until it's fixed, because the tooltip popup stays in the way of my code.

**Comment by lunaryorn** [comment]
@StreakyCobra I've turned this library into a global minor mode (`flycheck-pos-tip-mode`), which adds a hook to hide the tooltip after the next command.  Also, the tooltip automatically hides after five seconds now.

Please update and try whether that's better.

**Comment by StreakyCobra** [comment]
I can confirm that the 5 seconds timer works – the 60 seconds before was also working, just a little bit too long :-) – but the tooltip gets closed only by the timer. I tried to:

- Change line
- Insert text
- Open a new window
- Change buffer
- Change the focus to firefox
- …

And it stays for the 5 seconds in any case.

Is there anything else I should do to make it work, as it's a global minor mode now? Maybe it's a spacemacs problem?

----

I just updated my packages from melpa:

```elisp
(define-package "flycheck-pos-tip" "20151111.131" "Flycheck errors display in tooltip" '((dash "2.12") (flycheck "0.18") (pos-tip "0.4.6")) :url "https://github.com/flycheck/flycheck-pos-tip" :keywords '("tools" "convenience"))
```

I'm sure it's the last version as your last change is included (https://github.com/flycheck/flycheck-pos-tip/commit/f2459b4d71ce49988346e3dc445fb9b6896e78c0)

**Comment by lunaryorn** [comment]
@StreakyCobra Did you change your configuration to enable the new minor mode?

**Comment by StreakyCobra** [comment]
Sorry, I was assuming it was enabled by default, my bad. Indeed it works better, it escapes on actions within emacs, but not when changing the focus (i.e. changing to firefox, to a terminal, etc…)

If I am the only one encountering this problem, it may be something wrong on my side. I'm using i3-wm by the way.

**Comment by lunaryorn** [comment]
@StreakyCobra Does it matter that the tooltip stays when switching focus?  I mean, if you switch _away_ from Emacs, why would care for the error tooltip?

**Comment by StreakyCobra** [comment]
The problem is the tooltip stays in front of firefox, even if emacs is behind it.

It's why I am saying it could be related to my WM.

**Comment by joehillen** [comment]
I just reproduced @StreakyCobra's issue. I am also on i3. I'm worried this could be an issue with Emacs' tooltip implementation and not this plugin.

**Comment by lunaryorn** [comment]
@StreakyCobra Indeed, I can't reproduce that behaviour on OS X.  Anyhow, I've added code to hide the tooltip when Emacs looses focus, but you'll need at least Emacs 24.4 for that to work, as the corresponding hook is not available on earlier versions.

**Comment by StreakyCobra** [comment]
:+1: Many thanks, I'll try it once updated on melpa and give a feedback here.

**Comment by joehillen** [comment]
Is it supposed to take ~5 seconds for the tooltip to appear as well?

**Comment by lunaryorn** [comment]
@joehillen The tooltip appears after whatever you set `flycheck-display-errors-delay` to.

**Comment by joehillen** [comment]
```
flycheck-display-errors-delay is a variable defined in `flycheck.el'.
Its value is 0.9
```

Hmm, maybe it's a haskell-mode issue.

**Comment by StreakyCobra** [comment]
@lunaryorn It works now :+1: Thx for your help. On last detail: the `focus-out-hook` doesn't cancel the timer, so if we go on an error just before changing the focus, the the tip appears after the delay over the other window. But it's a minor annoyance :-)

**Comment by lunaryorn** [comment]
@StreakyCobra The latest `master` of Flycheck now cancels error display when Emacs looses focus, and re-starts it when Emacs gets the focus again.  That should properly hide and show the tooltip upon focus changes.  Again, focus hooks are 24.4 and upwards only, so you'll need to update Emacs if you're still on 24.3 or earlier.

**Comment by StreakyCobra** [comment]
:+1: I'll try it once in melpa, thx

**Comment by StreakyCobra** [comment]
@lunaryorn It works perfectly now! Many thanks.

**Comment by duianto** [comment]
This issue seems to have reappeared.

The tooltip remains visible when switching to another application on top of Emacs.

#### NixOS
- Emacs

![VirtualBoxVM_2020-08-26_08-17-34](https://user-images.githubusercontent.com/13420573/91270877-a0059180-e779-11ea-848c-d201b5a35bad.png)

- Switched (Alt + Tab) to Firefox

![VirtualBoxVM_2020-08-26_08-17-51](https://user-images.githubusercontent.com/13420573/91270897-a72c9f80-e779-11ea-8c35-f9fd9560e0ba.png)


flycheck-pos-tip-20200516.1600
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21)
NixOS 20.03

#### Windows
- Emacs

![2020-08-26_08-35-33](https://user-images.githubusercontent.com/13420573/91271136-01c5fb80-e77a-11ea-9293-d889d4d8ad3c.png)

- Switched (Alt + Tab) to Chrome

![2020-08-26_08-34-25](https://user-images.githubusercontent.com/13420573/91271147-05f21900-e77a-11ea-9a0b-94824d8e50d8.png)

flycheck-pos-tip-20200516.1600
GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29
Windows 1903
