### ISSUE TITLE
How to set a timeout?

### ISSUE THREAD

**Issue by zwb-ict** [flycheck/flycheck-pos-tip#9]
Tie tip appears too long for me, is there a way to set timeout? Thank you.

**Comment by lunaryorn** [comment]
@zwb-ict You can't, currently, but I'll add an option again.

**Comment by zwb-ict** [comment]
Thank you @lunaryorn!  Look forward to your update.

**Comment by lunaryorn** [comment]
@zwb-ict You can now change `flycheck-pos-tip-timeout`.  The default timeout is five seconds.

**Comment by zwb-ict** [comment]
Thank you @lunaryor! I updated, it's perfect!
